### ISSUE TITLE
add delete account

### ISSUE THREAD

**Issue by puncsky** [puncsky/guanxilab#121]
add a danger zone to https://www.guanxilab.com/settings/ and delete the account and associated profiles

**Comment by puncsky** [comment]
something similar to github 

<img width="1069" alt="Screen Shot 2019-10-30 at 2 35 19 AM" src="https://user-images.githubusercontent.com/1387285/67846156-f7859300-fabd-11e9-83e8-beb208c94831.png">

modal + message + button

**Comment by menq** [comment]
ok
